import Header from "@components/Header/Header";
import "./globals.css";
import { Poppins, Great_Vibes } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

const greatVibes = Great_Vibes({
  subsets: ["latin"],
  display: "swap",
  weight: ["400"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="bg-[#f8f8f8] text-base lg:text-lg text-neutral-900 ">
        <Header logoClassName={greatVibes.className} />
        <div className="m-5 md:m-7 lg:m-10">
          <div className="bg-white p-5 lg:p-10 rounded-xl shadow-lg">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
